# This is a GitHub Actions workflow file that automates the process of
# building and publishing your Python package to the Python Package Index (PyPI).

name: Publish Python Package to PyPI

# This workflow runs on two conditions:
# 1. When a new tag matching the pattern 'v*.*.*' (e.g., v0.1.0) is pushed.
# 2. When you manually trigger it from the GitHub Actions UI.
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    # This permission is essential for trusted publishing.
    # It allows the job to get a short-lived OIDC token from GitHub.
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: python -m pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1